# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Appsmith installation tasks
  tags:
    - setup-all
    - setup-appsmith
    - install-all
    - install-appsmith
  block:
    - name: Validate Appsmith configuration
      when: appsmith_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Appsmith
      when: appsmith_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Appsmith uninstallation tasks
  tags:
    - setup-all
    - setup-appsmith
  block:
    - name: Uninstall Appsmith
      when: not appsmith_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
